---
name: Mirror Repository

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: | 
            sudo apt-get update && sudo apt-get install -y ca-certificates
            sudo update-ca-certificates
            git config --global http.sslVerify false
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0            
      - name: Git Repo Sync
        uses: nickmcummins/git-repo-sync@v0.1.0
        with:
          target-url: https://gitlab.nickmcummins.com/forks/stracepy.git
          target-username: nickmcummins@linuxmail.org
          target-token: ${{ secrets.GITLAB_PAT }}
